<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Modules.Procurement.Contracts</RootNamespace>
		<AssemblyName>FSH.Modules.Procurement.Contracts</AssemblyName>
		<NoWarn>$(NoWarn);S2094</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
	</ItemGroup>

</Project>
