<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Modules.Ops</RootNamespace>
		<AssemblyName>FSH.Modules.Ops</AssemblyName>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;S3267</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
		<ProjectReference Include="..\Modules.Ops.Contracts\Modules.Ops.Contracts.csproj" />
		<ProjectReference Include="..\..\Ordering\Modules.Ordering.Contracts\Modules.Ordering.Contracts.csproj" />
		<ProjectReference Include="..\..\Inventory\Modules.Inventory.Contracts\Modules.Inventory.Contracts.csproj" />
		<ProjectReference Include="..\..\Procurement\Modules.Procurement.Contracts\Modules.Procurement.Contracts.csproj" />
		<ProjectReference Include="..\..\Warehouse\Modules.Warehouse.Contracts\Modules.Warehouse.Contracts.csproj" />
		<ProjectReference Include="..\..\Logistics\Modules.Logistics.Contracts\Modules.Logistics.Contracts.csproj" />
	</ItemGroup>

</Project>
