<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Procurement.Tests</RootNamespace>
		<AssemblyName>Procurement.Tests</AssemblyName>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<NoWarn>$(NoWarn);CA1515;CA1861;CA1707</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Shouldly" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="coverlet.collector" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Modules\Procurement\Modules.Procurement\Modules.Procurement.csproj" />
	</ItemGroup>

</Project>
